### ISSUE TITLE
s-left used, not imported

### ISSUE THREAD

**Issue by michaelcadilhac** [DarwinAwardWinner/ido-completing-read-plus#130]
At some place, the package uses the function `s-left` from the `s` package, but the `s` package is never `require`d, nor is it a dependency on MELPA.

**Comment by DarwinAwardWinner** [comment]
Thanks for catching this. I declared the dependency in the Cask file in the repo, but MELPA doesn't get its dependency info from that. And then the test suite requires s, so s is always loaded during testing, preventing discovery of this problem.

**Comment by michaelcadilhac** [comment]
My, you didn't even leave me enough time to wait.  Thanks!
