### ISSUE TITLE
Use memoization to simplify dynamic collection logic?

### ISSUE THREAD

**Issue by DarwinAwardWinner** [DarwinAwardWinner/ido-completing-read-plus#131]
See https://github.com/skeeto/emacs-memoize.

**Comment by DarwinAwardWinner** [comment]
If speed becomes an issue later, I can revisit this.

**Comment by DarwinAwardWinner** [comment]
Reopening because this will make it easier to solve #133.

**Comment by rprimus** [comment]
Sun Aug 13 19:33:43 BST 2017

Requiring 'memoize' completely breaks emacs.  Every operation yields:

```Cannot open load file: No such file or directory, memoize```

emacs must be stopped with ```kill -9```

Is there a way to state (in the package description) that emacs-memoize is a required package and have emacs automatically install the package?

**Comment by DarwinAwardWinner** [comment]
Memoize is definitely a MELPA package: http://melpa.org/#/memoize. ido-cr+ version 4.4 had an issue where the memoize dependency was not declared correctly, so MELPA didn't pick it up. This should be fixed in 4.5.

**Comment by rprimus** [comment]
Sun 13 Aug 2017 20:30:32 BST

Ahhh - coolio.  ```emacs -q``` and ```package-list-packages``` didn't show it.

Have just pulled the new version!

Cheers!!
