### ISSUE TITLE
Dynamic collection updates ignore restrictions

### ISSUE THREAD

**Issue by DarwinAwardWinner** [DarwinAwardWinner/ido-completing-read-plus#133]
After running `ido-restrict-to-matches`, dynamic completion updates can add back in items that don't satisfy the restriction. 

Example from https://github.com/DarwinAwardWinner/ido-completing-read-plus/issues/126#issuecomment-317880240:

```elisp
(completing-read
 "Describe variable: "
 (collection-as-function obarray)
 (lambda (vv)
   (setq vv (intern vv))
   (or (get vv 'variable-documentation)
       (and (boundp vv) (not (keywordp vv)))))
 t nil nil)
```

And then type `popup C-SPC type`. Completions are not restricted to variables that match "popup".

**Comment by DarwinAwardWinner** [comment]
cc @vspinu

**Comment by vspinu** [comment]
Thanks Ryan for quick fix. I think you forgot to include `memoise` in the dependencies ;)

I have updated and the restriction seem to work only with the most recent restriction. So if I do `cider- C-SPC mode-map C-SPC` I see candidates with `mode-map` but they don't contain `cider-`.  Can you see this?

**Comment by DarwinAwardWinner** [comment]
Yes, I found a logic error in the code. Can you try latest master (version 4.5)?

**Comment by vspinu** [comment]
Great. Updated and it works like a charm. Thanks!
