### ISSUE TITLE
Missing memoize package after update

### ISSUE THREAD

**Issue by hlolli** [DarwinAwardWinner/ido-completing-read-plus#136]
Memoize is not on my melpa seemingly.

```
error: Unable to activate package ‘ido-completing-read+’.
Required package ‘memoize-1.1’ is unavailable
```

**Comment by DarwinAwardWinner** [comment]
Are you using MELPA Stable?

**Comment by DarwinAwardWinner** [comment]
Actually, I just checked, and MELPA Stable does have memoize: https://stable.melpa.org/#/memoize

**Comment by hlolli** [comment]
No I only use unstable, the same one I got ido-completing-read+ from.

That may be irresponsible but there are just too many outdated packages on stable I think.

**Comment by DarwinAwardWinner** [comment]
Well, the memoize plane is definitely in both stable and unstable. I think you must have either outdated package information or a configuration error.

**Comment by hlolli** [comment]
Yes it's there, call me crazy but I looked at it this morning and didn't find it. I give this another try...

**Comment by hlolli** [comment]
Yes, it's suddenly there when I refreshed the packages. Refreshed often this morning, but in the meantime deleted this package, could have had an effect... ok thanks!
