### ISSUE TITLE
ido-ubiquitous and ido-completing-read+ has different REQUIRES

### ISSUE THREAD

**Issue by junjiemars** [DarwinAwardWinner/ido-completing-read-plus#139]
If Emacs version less than 24.4 will sucks.

* ido-ubiquitous
>    Status: Available -- [Install]
>    Version: 4.5
>   Requires: emacs-24.1, ido-completing-read+-4.5, cl-lib-0.5
>    Summary: Use ido (nearly) everywhere.

* ido-completing-read+
>    Status: Available -- [Install]
>    Version: 4.5
>   Requires: emacs-24.4, cl-lib-0.5, s-0.1, memoize-1.1
>    Summary: A completing-read-function using ido

When installing ```ido-ubiquitous``` will generate this:
```lisp
Debugger entered--Lisp error: (error "Package `emacs-24.4' is unavailable")
  signal(error ("Package `emacs-24.4' is unavailable"))
  error("Package `%s-%s' is unavailable" "emacs" "24.4")
  package-compute-transaction((ido-completing-read+ ido-ubiquitous) ((emacs (24 4)) (cl-lib (0 5)) (s (0 1)) (memoize (1 1))))
  package-compute-transaction((ido-ubiquitous) ((emacs (24 1)) (ido-completing-read+ (4 5)) (cl-lib (0 5))))
  package-install(ido-ubiquitous)
  #[257 "\300?\205^H^@\301^A!\207" [nil package-install] 3 "\n\n(fn I)"](ido-ubiquitous)```

**Comment by DarwinAwardWinner** [comment]
You're correct, I forgot to change the required Emacs version in ido-ubiquitous to match the one in ido-cr+. I'll fix this. However, note that ido-ubiquitous is a deprecated package that provides no functionality at all, so there's no reason you should be installing it anyway.
