### ISSUE TITLE
Problem with Magit

### ISSUE THREAD

**Issue by contrapunctus-1** [DarwinAwardWinner/ido-completing-read-plus#140]
GNU Emacs 24.5.1 (i686-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-12 on x86-grnet-01, modified by Debian
ido-ubiquitous v4.2, commit hash 02f21215ce5ef2234c0e58dac9ec181cfc0900c1

Steps to reproduce
1. Enable ido-ubiquitous-mode
2. Run magit-status
3. Place point at a filename
4. Type `E s` or `M-x magit-ediff-stage`
5. Error message - `Invalid function: ("<filename>.<extension>")`
[Backtrace](http://paste.debian.net/986993/)
(Somehow, I could never paste the entire backtrace here - it always got truncated after some point.)

Error does not occur with ido-ubiquitous-mode disabled.

**Comment by DarwinAwardWinner** [comment]
Can you indicate the values of `ido-cr+-function-blacklist`? It should contain `magit-builtin-completing-read`.

**Comment by contrapunctus-1** [comment]
Sorry I took so long to get back on this - ido-cr+-function-blacklist does contain magit-builtin-completing-read -

> (read-file-name-internal read-buffer todo-add-category gnus-emacs-completing-read gnus-iswitchb-completing-read grep-read-files magit-builtin-completing-read ess-completing-read Info-read-node-name tmm-prompt)

**Comment by DarwinAwardWinner** [comment]
Hmm. If `magit-builtin-completing-read` is in `ido-cr+-function-blacklist`, then ido-cr+ should never even be used, unless you've set `magit-completing-read-function` to `magit-ido-completing-read`.

**Comment by contrapunctus-1** [comment]
The value of `magit-completing-read-function` is `magit-builtin-completing-read`.

**Comment by DarwinAwardWinner** [comment]
Ok. So ido completion should never even be happening, which makes this error very weird. Could you post the stack trace again? The original paste seems to have expired. I'll save it to my disk this time.

**Comment by contrapunctus-1** [comment]
http://paste.debian.net/993940/

**Comment by DarwinAwardWinner** [comment]
I'm sorry I didn't get to the second paste in time either. Could you just email the backtrace to me? (Find my email in my profile.)

**Comment by DarwinAwardWinner** [comment]
As this has been inactive for over a year, I'm going to close it. Please create a new issue if this is still a problem.
