### ISSUE TITLE
Issues with Emacs 26

### ISSUE THREAD

**Issue by ylluminarious** [DarwinAwardWinner/ido-completing-read-plus#141]
I've recently updated to Emacs 26.0.90. It seems that `smex` and `ido-cr+` are both affected by an odd bug, wherein when I try to select certain items from the minibuffer, I get errors like this:

```
Error in post-command-hook (ido-exhibit): (error "Attempt to modify read-only object" "eval")
```

That happened when, for example, I tried to do `C-h f eval-region`. But my command never got past the `ev` in `eval-region`. It seems that as soon as the item is selected, this error appears and the Ido completion list is gone. I also did `toggle-debug-on-error` to get a backtrace of the error, but no dice. No backtrace would appear in spite of this error occurring.

**Comment by muflax** [comment]
It's a bug in ido.el. Fixed upstream, see https://github.com/emacs-mirror/emacs/commit/b78332c3c646be12d252a637ce0fc949919a840b, so presumably the next pretest will be fine.

**Comment by DarwinAwardWinner** [comment]
Ok, I'm going to close this.

**Comment by ylluminarious** [comment]
@muflax Thanks, good to know.
