### ISSUE TITLE
ido performance issues on emacs26+

### ISSUE THREAD

**Issue by TatriX** [DarwinAwardWinner/ido-completing-read-plus#143]
I did update to the latest emacs git version (also tested emacs26 branch) and I'm having minor but noticable performance issues. `(profile-report)`  shows that the most of the cpu cycles spent in the `ido-read-internal`. Probably it's not the right place to ask or even not the main source problem, but maybe you had experienced similar issues and could help me investigate problem futher?

My ido config:
```elisp
(require 'ido)
(ido-mode 1)
(ido-everywhere 1)
(setq ido-enable-flex-matching t)

(use-package ido-completing-read+
  :config
  (ido-ubiquitous-mode 1))

```

**Comment by DarwinAwardWinner** [comment]
I'm still on Emacs 25, so I can't really tell you what's different in Emacs 26. `ido-read-internal` is the function that implements ido completion, so it's not really surprising that most of the CPU time would be spent there. Is there any particular command or function that's giving you slow completion? Or is it only happening with large collections?

**Comment by TatriX** [comment]
Well completion of the `C-x C-f` is slower. It's slow on initial mini buffer opening and afterwards when I cycle through the candidates or enter directories.

Also `C-h k C-f` is slow, like it takes half a second to open the help window. On the other side `C-x 3` opens second window immediately.

**Comment by DarwinAwardWinner** [comment]
I'm afraid ido-cr+ has nothing to do with either of those examples, unless there is a bug that is affecting normal Emacs operation. Have you verified that the slowdown only occurs when ido-cr+ is loaded/enabled?

**Comment by TatriX** [comment]
I think it's the same with `emacs -Q`. Sure, probably, it's not ido-cr+ fault. Probably it's related to emacs26 itself, but for some reason it's mostly seen when using ido. I would be very appreciate if someone could confirm if the problem is local to me or not.

**Comment by DarwinAwardWinner** [comment]
I'm sorry, I can't confirm this since I don't use Emacs 26. And since this has nothing to do with ido-cr+, this isn't the right place to look for help. You'll probably have better luck with the Emacs mailing list, since ido is part of Emacs.
