### ISSUE TITLE
Emacs refuses to remove `ido-ubiquitous`

### ISSUE THREAD

**Issue by JoeyAcc** [DarwinAwardWinner/ido-completing-read-plus#150]
Not sure if it's an Emacs issue or an issue related to this project, but cleaning up files e.g. the entire `ido-ubiquitous` just plain fails to do the job.

Reproduction is easy, if you (like me) have an install that started out with `ido-ubiquitous` but got upgraded to `ido-completing-read-plus`.  Just try to remove `ido-ubiquitous` using e.g. `M-x package-remove`.  Emacs will say that it was deleted, yet when restarting Emacs I still get a warning buffer saying the old project is installed:

````
Warning (ido-ubiquitous): The ido-ubiquitous package is now redundant. All functionality, including ido-ubiquitous-mode, has been merged into the ido-completing-read+ package. You should replace ido-ubiquitous with ido-completing-read+ in your Emacs config. For more information, see:
https://github.com/DarwinAwardWinner/ido-ubiquitous#version-40-changes
````

**Comment by DarwinAwardWinner** [comment]
Is it possible that your Emacs config has a fixed list of packages that it automatically installs on startup?

**Comment by JoeyAcc** [comment]
I myself haven't added any.  But I do use [Prelude](https://github.com/bbatsov/prelude), maybe that is connected to this somehow?

**Comment by DarwinAwardWinner** [comment]
I'm not a Prelude user, so I coulnd't tell you. Looking at the code, it doesn't seem to be directly installing ido-ubiquitous, but perhaps one of the other packages that it installs still has a lingering dependency on it that has not been updated.

**Comment by DarwinAwardWinner** [comment]
This issue should no longer occur as of the next MELPA update, since ido-ubiquitous will no longer be available for installation from MELPA
