### ISSUE TITLE
ido-cr+ hangs in Info-menu

### ISSUE THREAD

**Issue by patxoca** [DarwinAwardWinner/ido-completing-read-plus#151]
In order to reproduce this behaviour with `emacs -Q` evaluate the following code (adjust directories as required):

```emacs-lisp
(push "/home/aroda/.emacs.d/elpa/ido-completing-read+-4.7" load-path)
(push "/home/aroda/.emacs.d/elpa/s-1.12.0" load-path)
(push "/home/aroda/.emacs.d/elpa/memoize-1.1" load-path)

(require 'ido)
(ido-mode 1)

(require 'ido-completing-read+)
(ido-ubiquitous-mode 1)
```
Then type `C-h i m e m a c s ` (the actual search is irrelevant) and keep pressing the previous/next keys. After some key presses it will block. I've been unable to spot a pattern, keep pressing previous/next randomly for a while.

In emacs 25.2.1 and emacs 25.3.1 CPU usage gets 100%. If started with `-nw`it dumps core. In graphical mode pressing `C-g` repeatedly regains control.
In emacs 26.0.91 it displays a warning but no hang:

```emacs-lisp
Warning (ido-cr+): Disabling dynamic update due to error: (circular-list ("realpath" "readlink" "pwd" "ptx" "pr" "printf" "printenv" "pooltype" "pltotf" "pktype" "pktogf" "pathchk" "patgen" "patch" "paste" "od" "numfmt" "nproc" "nohup" "nl" "nice" "mv" "mpost" "mltex" "mktemp" "mknod" "mkfifo" "mkdir" "mft" "mf" "md5sum" "ls" "logname" "locate" "ln" "link" "kill" "join" ... )
```

For now I've  blacklisted `Info-menu` in my config.

**Comment by DarwinAwardWinner** [comment]
Sure enough, I can reproduce this on my computer. I'll look into it when I get the chance.

**Comment by DarwinAwardWinner** [comment]
This is likely related to #146.

**Comment by patxoca** [comment]
I've tried applying the patch from #146 and still hangs, in emacs 25.x. Tomorrow I'll do some more testing.

**Comment by DarwinAwardWinner** [comment]
Yeah, #146 isn't actually fixed yet. I was just making the link between the two issues since they seem to be related.

**Comment by patxoca** [comment]
I can reproduce the hang with the procedure you describe.

I was playing with ido-cr+ and setting `ido-cr+-dynamic-update-idle-time` to 25 (effectively disabling dynamic updates ... I think ... I don't understand most of ido-cr+ or what dynamic updates are for) removed the hang. This seems to confirm that dynamic update code is somehow involved in the bug (?).

**Comment by patxoca** [comment]
Thanks for fixing the issue!
