### ISSUE TITLE
Can it replace completion-list-mode?

### ISSUE THREAD

**Issue by vemv** [DarwinAwardWinner/ido-completing-read-plus#158]
Hi again,

I wonder if this library can replace `completion-list-mode` (the `*Completions*` buffer).

`*Completions*` appears when hitting TAB on `eval-expression`, or in IELM.

Thanks - Victor

**Comment by DarwinAwardWinner** [comment]
No, this package has nothing to do with `completion-list-mode`. It only allows usage of ido within `completing-read`.
