### ISSUE TITLE
completion-auto-help not respected

### ISSUE THREAD

**Issue by wyuenho** [DarwinAwardWinner/ido-completing-read-plus#172]
The minibuffer has a custom option called `completion-auto-help`, which prevents the minibuffer help buffer from popping up when tabbing on an empty input. When `ido-ubiquitous-mode` is enabled.

Reproduction:

1. `(setq icomplete-mode t)`
2. `(setq completion-auto-help nil)`
2. `(ido-ubiquitous-mode t)`
3.  M-x describe-function RET TAB
4. The minibuffer help buffer pops up.

Expectation:
No minibuffer help buffer pops up

**Comment by DarwinAwardWinner** [comment]
Can you tell me if the following works for you? If so, I'll incorporate a version of it into the next ido-cr+ release.

```elisp
(define-advice ido-completion-help (:around (orig-fun &rest args) respect-completion-auto-help)
  "Don't show *Ido Completions* buffer when `completion-auto-help' is nil."
  (when completion-auto-help
    (apply orig-fun args)))
```

**Comment by DarwinAwardWinner** [comment]
Note that ido has its own setting, `ido-cannot-complete-command`, which you can set to `ignore` to achieve a similar effect. Ultimately, to the extent that this is a bug, it is a bug in ido itself. Hence, I've reported it to the Emacs bug tracker: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=41340

**Comment by wyuenho** [comment]
That snippet doesn't work. The help buffer should still pop up after pressing ? when completion-auto-help is nil. There's also no reliable way to ignore appropriately because ido-completion-help is called interactively from ido-complete.

**Comment by DarwinAwardWinner** [comment]
Does setting `ido-cannot-complete-command` to `ignore` do what you want?

**Comment by wyuenho** [comment]
Yep that does it. Thanks!

**Comment by DarwinAwardWinner** [comment]
Closing this as it will be addressed in https://debbugs.gnu.org/cgi/bugreport.cgi?bug=41340
