### ISSUE TITLE
CPU usage with Ido-crp

### ISSUE THREAD

**Issue by jdtsmith** [DarwinAwardWinner/ido-completing-read-plus#176]
I often find my Emacs CPU usage spiked at 130%, only when using `ido-ubiquitious 1`, and after invoking a command like `imenu-anywhere`.  The profiler then reports something like:

```
- command-execute                                                7481  99%
 - call-interactively                                            7481  99%
  - apply                                                        7481  99%
   - call-interactively@ido-cr+-record-current-command           7481  99%
    - apply                                                      7481  99%
     - #<subr call-interactively>                                7481  99%
      - byte-code                                                7478  99%
       - read--expression                                        7478  99%
        - read-from-minibuffer                                     55   0%
         + command-execute                                         13   0%
         + redisplay_internal (C function)                          3   0%
         + timer-event-handler                                      3   0%
         + #<compiled 0x1ff7fa5227c5>                               1   0%
         + undo-auto--undoable-change                               1   0%
      + funcall-interactively                                       3   0%
+ redisplay_internal (C function)                                   2   0%
+ ...      
```

Not sure why the eventual call to read--expression which `ido-cr+-record-current-command` kicks off would misbehave like this.  Using the latest emacs-mac port.

**Comment by DarwinAwardWinner** [comment]
I think `call-interactively@ido-cr+-record-current-command` is a red herring here, because all that is just a wrapper function that let-binds a single variable and then calls the real `call-interactively`. However, it sounds like ido-completing-read+ may still be involved somehow. Does this happen with all commands or only specific ones?

In any case, I don't have experience using the profiler. Can you describe the exact sequence of keys/commands to produce something like the above profiling output, so I can attempt to reproduce it on my machine?

**Comment by jdtsmith** [comment]
If you have a high CPU load for no reason, you can `M-x profiler-start [Ret]`, choose `cpu`, then wait some time (10-15s) and `M-x profiler-report`.  Then when done `M-x profiler-stop`.  I've done this several times when running >100% CPU and it always seems to be burning cycles in `read--expression`.  Not entirely consistent with `imenu-anywhere`, but I haven't encountered this at all when disabling icr+.

**Comment by DarwinAwardWinner** [comment]
So you're saying that Emacs consumes high amounts of CPU but remains responsive, such that you can execute commands and such? That's very odd. I'll try to look into it.

**Comment by DarwinAwardWinner** [comment]
Hmm, looking into things, it seems that `read--expression` is an internal function used to read a lisp expression for the interactive command `eval-expression`, i.e. the command normally bound to `M-:`. This function doesn't call ido or `completing-read` at all. So no matter how I slice it, I can't see any way that ido-cr+ could be involved here.

**Comment by jdtsmith** [comment]
Exactly, high CPU usage but still usable, nothing to quit/cancel/etc.  Usually I notice my fans whirring.  I agree it's probable that ido-cr+ merely kicks off the activity that eventually leads to this situation.  I'll keep an eye on it.
