### ISSUE TITLE
`read-directory-name` and `read-file-name` are now disabled

### ISSUE THREAD

**Issue by vspinu** [DarwinAwardWinner/ido-completing-read-plus#178]
Evaluating `(read-directory-name "prompt: ")` does not trigger directory completion anymore. Same for `read-file-name`. 

It steams from the fact that `ido-completing-read+` receives `read-file-name-internal` as `collection` argument which is now disabled in `ido-cr+-disable-list`. 

It renders ido-ubiquitous disabled for the main use case of ido-mode. Ido-mode does not kick in on itself, even though it's globally active for me.

Tested on emacses 29 and 26 with ido-cr+ `20210529.1318`.

I know this behavior is there for at least  year now but I have noticed it only now on my recent update. I have updated my packages back in January but for an unclear reason this issues didn't pop up earlier. So I am a bit confused :thinking:

**Comment by vspinu** [comment]
I actually tracked it down to how I activate `ido-everywhere`. I used to simply `(qset ido-everywhere t)`. Now this no longer works, so have to initialize explicetly with `(ido-everywhere t)`. 

I wonder if `ido-ubiquitous` should check if `ido-everywhere` is enabled and enabled if not. WDYT?

At least, it would be useful if this split of functionality between ido-ubiquitous and ido-everywhere could be documented in some  visible place like docstring of `ido-ubiquitous-mode` for example.

**Comment by DarwinAwardWinner** [comment]
Remember that ido-cr+ has nothing to do with reading file names. That is ido's job. I have actually documented how to enable ido in as many places as possible in the README file. Perhaps you're right that it should be enabled somewhere in a docstring, that's accessible from Emacs itself.

**Comment by DarwinAwardWinner** [comment]
I've thought about this, and I think it's not reasonable to do anything here. I could add a warning or message if ido-ubiquitous-mode is enabled without ido-everywhere, but what if the user's init file enables them in the wrong order? They would get a misleading message about enabling a mode that is already enabled by the time they see the message. So I think I just need to trust the user to know about ido-everywhere or read the README.
