### ISSUE TITLE
M-y (yank-pop) does not preview changes when using this plugin

### ISSUE THREAD

**Issue by nullishamy** [DarwinAwardWinner/ido-completing-read-plus#180]
Hello!

Big fan of the plugin, however one slight issue is that M-y no longer previews each entry as you cycle it (as opposed to searching). Tried to disable cr+ from activating on it with the disable list but it does not want to respect it. Any ideas on how to get that config to work again?

**Comment by DarwinAwardWinner** [comment]
Hi, thanks for the bug report. I'm not familiar with yank-pop, so can you provide a specific sequence of actions I can perform starting from a newly opened Emacs to see the problem?

**Comment by nullishamy** [comment]
Sure! With a line of sample text on a line:

;; populating the kill ring
C-a 
C-SPC
C-e
M-w
M-b
M-d

;; go to a new line
M-y
C-s / C-r

When doing the final steps, it should preview the selected entry within the buffer

**Comment by DarwinAwardWinner** [comment]
According to the help text and my testing, the sequence of inputs you described causes `yank-pop` to effectively dispatch to `yank-from-kill-ring`, which AFAIK doesn't preview the text directly in the buffer but instead prompts for a selection using `completing-read`. On my Emacs, pressing M-y immediately after a C-y (`yank`) invokes the normal `yank-pop` behavior inserting the relevant killed text directly into the buffer, regardless of whether `ido-uniquitous-mode` is enabled or not. Conversely, `yank-from-kill-ring` never inserts any text until after I've selected it, and again `ido-ubiquitous-mode` does not change its behavior other than enabling ido completion for the selection. I'm not seeing the behavior you want even in a fresh `emacs -Q` session with nothing loaded.

**Comment by nullishamy** [comment]
Think my memory was faulty on that one, apologies for the inconvenience. Least this can be up in case someone else has the same! Closing this one out.
