### ISSUE TITLE
completion-extra-properties

### ISSUE THREAD

**Issue by daimrod** [DarwinAwardWinner/ido-completing-read-plus#8]
`completion-extra-properties` doesn't seem to be supported by ido.

https://github.com/daimrod/manual-tagging/blob/master/manual-tagging.el#L85

I use it here to customize the _completion_ buffer, it lets me display additional information.

**Comment by cichli** [comment]
@DarwinAwardWinner adding annotation support to `ido-completion-help` sounds like a great solution, and `:exit-function` seems certainly doable. Do you still plan to implement support for this? :-)

If not, I'm happy to take a stab at a PR.

**Comment by DarwinAwardWinner** [comment]
I'm not currently planning to implement this, but I would certainly be willing to merge a patch implementing it. Make sure you check all the properties in `completion-extra-properties` and fall back if any of them are ones your code can't handle.
